#!/bin/sh

make clean;
make;
sudo make install;

psql <<EOF
	\timing
	SET jit=on;
	SET work_mem="1MB";
	DROP EXTENSION generate_up_down_series;
	CREATE EXTENSION generate_up_down_series;

	\set n 340
	\set m 570
	\set rows 2 * :n * :m

	SELECT count(*) AS warm_up FROM (SELECT generate_up_down_series_evan(:n,:m)) AS t;
	SELECT count(*) AS warm_up FROM (
		WITH cte AS ( SELECT ARRAY(SELECT GENERATE_SERIES(1, :n)) AS arr)
		SELECT UNNEST (
			( SELECT ARRAY_CAT(c.arr, SORT(c.arr, 'DESC')) FROM cte c)
		) FROM GENERATE_SERIES(1, :m)
	) AS t;
	\echo
	\echo
	\echo
	\echo
	\echo
	\echo
	\echo

	\echo VERACE_QUERY [number to beat]
	SELECT count(*) FROM (
		WITH cte AS ( SELECT ARRAY(SELECT GENERATE_SERIES(1, :n)) AS arr)
		SELECT UNNEST (
			( SELECT ARRAY_CAT(c.arr, SORT(c.arr, 'DESC')) FROM cte c)
		) FROM GENERATE_SERIES(1, :m)
	) AS t;
	\echo
	\echo

	\echo XXXXX VALUEPERCALL XXXXX
	\echo SELECT count(*) FROM (SELECT generate_series(1,:rows)) AS t;
	      SELECT count(*) FROM (SELECT generate_series(1,:rows)) AS t;
	
	\echo SELECT count(*) FROM (SELECT generate_up_down_series_evan(:n,:m)) AS t;
	      SELECT count(*) FROM (SELECT generate_up_down_series_evan(:n,:m)) AS t;
	

	\echo XXXXX MATERIALIZED XXXXX
	\echo SELECT count(*) FROM (SELECT * FROM generate_series(1,:rows)) AS t;
	      SELECT count(*) FROM (SELECT * FROM generate_series(1,:rows)) AS t;
	
	\echo SELECT count(*) FROM (SELECT * FROM generate_up_down_series_evan(:n,:m)) AS t;
	      SELECT count(*) FROM (SELECT * FROM generate_up_down_series_evan(:n,:m)) AS t;
EOF
